# Generated by Django 2.2.14 on 2022-05-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_text_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text_field', models.CharField(default='your message', max_length=1000)),
            ],
        ),
    ]
