# Generated by Django 2.2.14 on 2022-05-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_message_text_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
    ]
