# Generated by Django 2.2.14 on 2022-05-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_message_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message_text_class',
        ),
        migrations.AddField(
            model_name='message',
            name='message_text_field',
            field=models.CharField(default='your message', max_length=1000),
        ),
    ]
