# Generated by Django 2.2.14 on 2022-05-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20220520_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email_address',
            field=models.EmailField(default='Email address', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='full_name',
            field=models.CharField(default='Your name', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text_field',
            field=models.CharField(default='Your message', max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Subject', max_length=300),
        ),
    ]
