# Generated by Django 2.2.14 on 2022-05-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20220521_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_text_field',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='message',
            name='email_address',
            field=models.CharField(default='Email address', max_length=200),
        ),
    ]
