# Generated by Django 2.2.14 on 2022-07-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20220521_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email_address',
            field=models.EmailField(default='Email address', max_length=200),
        ),
    ]
