# Generated by Django 4.0.2 on 2022-04-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cyberspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberspace',
            name='image',
            field=models.ImageField(default='cyber_def.jpg', upload_to='cyberspace'),
        ),
    ]
