# Generated by Django 4.0.2 on 2022-04-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_messageform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageForm',
        ),
        migrations.AddField(
            model_name='cyberspace',
            name='credit',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
