# Generated by Django 4.0.2 on 2022-04-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220426_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Cyber', max_length=100)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
