# Generated by Django 4.0.2 on 2022-04-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='cyber_def.jpg', upload_to='cyberspace'),
        ),
    ]
