# Generated by Django 4.0.2 on 2022-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220426_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='cyber_def.jpg', upload_to='service'),
        ),
    ]
