# Generated by Django 2.2.14 on 2022-05-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220513_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='brand_images')),
            ],
        ),
        migrations.CreateModel(
            name='Org_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('org_mail', models.CharField(max_length=100)),
                ('org_mobile', models.CharField(max_length=100)),
                ('org_address', models.CharField(max_length=500)),
                ('image', models.ImageField(default='default.jpg', upload_to='org_info_image')),
            ],
        ),
    ]
