# Generated by Django 2.2.14 on 2022-07-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_brands_list_org_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(default='comments', max_length=2000),
            preserve_default=False,
        ),
    ]
