# Generated by Django 2.2.14 on 2022-07-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20220704_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(default=False, max_length=2000),
        ),
    ]
